version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: patient-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: patientdb
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  patientservice:
    build: .
    container_name: patient-service
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/patientdb
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/patients/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


volumes:
  mongo_data: